=== 1ec5/openaddresses/schema/source_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Source",
    "description": "An OpenAddresses source",
    "type": "object",
    "required": ["type", "data", "coverage"],
    "additionalProperties": false,
    "properties": {
      "type": {
        "type": "string",
        "enum": ["http", "ftp", "ESRI"]
      },
      "data": {
        "type": "string",
        "format": "uri"
      },
      "coverage": {
        "type": "object",
        "$ref": "#/definitions/coverage"
      },
      "website": {
        "type": "string",
        "format": "uri"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "conform": {
        "type": "object",
        "$ref": "#/definitions/conform"
      },
      "compression": {
        "type": "string"
      },
      "license": {
        "type": "string"
      },
      "note": {
        "type": "string"
      },
      "attribution": {
        "type": "string"
      },
      "language": {
        "type": "string"
      },
      "year": {
        "type": "string"
      },
      "skip": {
        "type": "boolean"
      }
    },
    "definitions": {
      "coverage": {
        "required": ["country"],
        "properties": {
          "country": {
            "type": "string"
          }
        }
      },
      "conform": {
        "properties": {
          "type": {
            "type": "string",
            "enum": ["geojson", "shapefile", "shapefile-polygon"]
          },
          "addrtype": {
            "type": "string"
          },
          "accuracy": {
            "type": "integer",
            "minimum": 0,
            "exclusiveMinimum": true
          },
          "csvsplit": {
            "type": "string"
          },
          "srs": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "encoding": {
            "type": "string"
          }
        }
      }
    }
}

=== 1ec5/openaddresses/sources/us/fl/st-lucie.json
{
    "coverage": {
        "US Census": {
            "geoid": "12111",
            "name": "St. Lucie County",
            "state": "Florida"
        },
        "country": "us",
        "state": "fl",
        "county": "St. Lucie"
    },
    "data": "http://www.stlucieco.gov/home/showdocument?id=2739",
    "type": "http",
    "compression": "zip",
    "conform": {
        "number": "StreetNumb",
        "street": "StreetLabe",
        "unit": "AptSuite",
        "city": "City",
        "postcode": "ZipCode",
        "type": "shapefile",
        "file": "AddressMaster.shp"
    }
}

=== 1ec5/openaddresses/sources/us-nc-rutherford.json
{
    "coverage": {
        "US Census": {
            "geoid": "37161",
            "name": "Rutherford County",
            "state": "North Carolina"
        },
        "country": "us",
        "state": "nc",
        "county": "Rutherford"
    },
    "data": "http://arcgis.webgis.net/arcgis/rest/services/NC/Rutherford/MapServer/4",
    "license": "Indemnification",
    "type": "ESRI"
}

=== 1ec5/openaddresses/sources/ca-on-burlington.json
{
    "coverage": {
        "country": "ca",
        "state": "on",
        "city": "Burlington"
    },
    "data": "http://cms.burlington.ca/AssetFactory.aspx?did=30050",
    "website": "http://cms.burlington.ca/Page12956.aspx",
    "license": "http://cms.burlington.ca/AssetFactory.aspx?did=18762",
    "type": "http",
    "compression": "zip",
    "conform": {
        "merge": [
            "street",
            "strtype"
        ],
        "lon": "x",
        "lat": "y",
        "number": "housenum",
        "street": "auto_street",
        "type": "shapefile"
    }
}

=== 1ec5/openaddresses/sources/us-oh-tuscarawas.json
{
    "coverage": {
        "US Census": {
            "geoid": "39157",
            "name": "Tuscarawas County",
            "state": "Ohio"
        },
        "country": "us",
        "state": "oh",
        "county": "Tuscarawas"
    },
    "data": "http://gis3.oit.ohio.gov/LBRS/_downloads/TUS_ADDS.zip",
    "type": "http",
    "compression": "zip",
    "conform": {
        "merge": [
            "STR_NAME",
            "STR_TYPE"
        ],
        "lon": "x",
        "lat": "y",
        "number": "ADDR_NUM",
        "street": "auto_street",
        "type": "shapefile",
        "postcode": "zip"
    }
}

=== 1ec5/openaddresses/sources/us-oh-fairfield.json
{
    "coverage": {
        "US Census": {
            "geoid": "39045",
            "name": "Fairfield County",
            "state": "Ohio"
        },
        "country": "us",
        "state": "oh",
        "county": "Fairfield"
    },
    "data": "http://gis3.oit.ohio.gov/LBRS/_downloads/FAI_ADDS.zip",
    "type": "http",
    "compression": "zip",
    "conform": {
        "merge": [
            "NAME",
            "TYPE"
        ],
        "lon": "x",
        "lat": "y",
        "number": "HOUSENUM",
        "street": "auto_street",
        "type": "shapefile"
    }
}

=== 1ec5/openaddresses/sources/us-wi-green.json
{
    "coverage": {
        "US Census": {
            "geoid": "55045",
            "name": "Green County",
            "state": "Wisconsin"
        },
        "country": "us",
        "state": "wi",
        "county": "Green"
    },
    "data": "http://landrecords.greencountywi.org/arcgis/rest/services/GreenCo_GIS/MapServer/1",
    "type": "ESRI",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "numb",
        "street": "street",
        "type": "geojson"
    }
}

=== 1ec5/openaddresses/sources/tw/mia/regionwide-zh.json
{
    "coverage": {
        "ISO 3166": {
            "alpha2": "TW-ILA",
            "country": "Taiwan"
        },
        "country": "tw"
    },
    "data": "http://ja.miaoli.gov.tw/arcgis/rest/services/Miaoli/miaoliDpDynamic_B/FeatureServer/1",
    "type": "ESRI",
    "language": "zh",
    "conform": {
        "type": "geojson",
        "number": {
          "function": "remove_prefix",
            "field": "ADDRESSALL",
            "field_to_remove": "ROAD"
        },
        "street": {
            "function": "join",
            "fields": ["ROAD","LANE","ALLEY"],
            "separator": ""
        },
        "city": "VILLAGE",
        "district": "TOWNN"
    }
}

=== 1ec5/openaddresses/sources/us/ga/city_of_johns_creek.json
{
    "coverage": {
        "US Census": {
            "geoid": "1342425",
            "name": "City of John's Creek",
            "state": "ga"
        },
        "country": "us",
        "state": "ga",
        "county": "Fulton",
        "city": "John's Creek"
    },
    "data": "https://services1.arcgis.com/bqfNVPUK3HOnCFmA/arcgis/rest/services/Address_Points/FeatureServer/0",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": "StNumber",
        "street": [
            "PreMod",
            "PreDir",
            "PreType",
            "Name",
            "PostType",
            "PostDir",
            "PostMod"
        ],
        "unit": "UnitActual",
        "city": "City",
        "region": "State",
        "postcode": "Zip"
    }
}
