=== 1ec5/openaddresses/schema/source_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Source",
    "description": "An OpenAddresses source",
    "type": "object",
    "required": ["type", "data", "coverage"],
    "additionalProperties": false,
    "properties": {
      "type": {
        "type": "string",
        "enum": ["http", "ftp", "ESRI"]
      },
      "data": {
        "type": "string",
        "format": "uri"
      },
      "coverage": {
        "type": "object",
        "$ref": "#/definitions/coverage"
      },
      "website": {
        "type": "string",
        "format": "uri"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "conform": {
        "type": "object",
        "$ref": "#/definitions/conform"
      },
      "compression": {
        "type": "string"
      },
      "license": {
        "type": "string"
      },
      "note": {
        "type": "string"
      },
      "attribution": {
        "type": "string"
      },
      "language": {
        "type": "string"
      },
      "year": {
        "type": "string"
      },
      "skip": {
        "type": "boolean"
      }
    },
    "definitions": {
      "coverage": {
        "required": ["country"],
        "properties": {
          "country": {
            "type": "string"
          }
        }
      },
      "conform": {
        "properties": {
          "type": {
            "type": "string",
            "enum": ["geojson", "shapefile", "shapefile-polygon"]
          },
          "addrtype": {
            "type": "string"
          },
          "accuracy": {
            "type": "integer",
            "minimum": 0,
            "exclusiveMinimum": true
          },
          "csvsplit": {
            "type": "string"
          },
          "srs": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "encoding": {
            "type": "string"
          }
        }
      }
    }
}

=== 1ec5/openaddresses/sources/us-ca-monterey_county.json
{
    "coverage": {
        "US Census": {
            "geoid": "06053",
            "name": "Monterey County",
            "state": "California"
        },
        "country": "us",
        "state": "ca",
        "county": "Monterey"
    },
    "attribution": "Monterey County",
    "data": "http://montereycountyopendata.montereyco.opendata.arcgis.com/datasets/02d744cef89148c6947ef704abbff753_0.geojson",
    "website": "http://montereycountyopendata.montereyco.opendata.arcgis.com/datasets/02d744cef89148c6947ef704abbff753_0",
    "license": "http://montereycountyopendata.montereyco.opendata.arcgis.com/datasets/02d744cef89148c6947ef704abbff753_0",
    "type": "http",
    "year": "2014",
    "note": "Download at that URL can be slow"
}

=== 1ec5/openaddresses/sources/us-wi-outagamie.json
{
    "coverage": {
        "US Census": {
            "geoid": "55087",
            "name": "Outagamie County",
            "state": "Wisconsin"
        },
        "country": "us",
        "state": "wi",
        "county": "Outagamie"
    },
    "data": "ftp://FTPGISWEBREAD:ftpgiswebread@ftp.co.outagamie.wi.us/AddressPointsSHAPE.zip",
    "type": "ftp",
    "compression": "zip",
    "skip": true
}

=== 1ec5/openaddresses/sources/us/wi/city_of_milwaukee.json
{
    "coverage": {
        "country": "us",
        "state": "wi",
        "city": "Milwaukee"
    },
    "type": "ESRI",
    "data": "http://maps.milwaukee.gov/ArcGIS/rest/services/LMS/LMS_APO/MapServer/1",
    "conform": {
        "type": "geojson",
        "numnber": "HSE_NBR",
        "street": [
            "DIR",
            "STREET",
            "STTYPE"
        ],
        "postcode": "ZIP_CODE",
        "city": "CITY"
    }
}

=== 1ec5/openaddresses/sources/us/ca/city_of_los_angeles.json
{
    "coverage": {
        "geometry": {
            "type": "Point",
            "coordinates": [ -118.2439, 34.0544 ]
        },
        "country": "us",
        "state": "ca",
        "city": "Los Angeles"
    },
    "data": "http://zimas.lacity.org/arcgis/rest/services/D_QUERYLAYERS/MapServer/11",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": {
            "function": "prefixed_number",
            "field": "Address"
        },
        "street": {
            "function": "postfixed_street",
            "field": "Address"
        },
        "postcode": "Zip"
    }
}

=== 1ec5/openaddresses/sources/co/ant/medellin.json
{
    "coverage": {
        "country": "co",
        "region": "ant",
        "city": "Medell√≠n",
        "geometry": { "type": "Point", "coordinates": [-75.59, 6.23] }
    },
    "data": "https://www.medellin.gov.co/arcgis/rest/services/ServiciosPlaneacion/Pot_base1/MapServer/0",
    "website": "https://www.medellin.gov.co/geomedellin/",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": "PLACA",
        "street": ["TIPO_VIA", "NUMERO_VIA", "APENDICE_VIA"]
    }
}

=== 1ec5/openaddresses/sources/us/nc/yancey.json
{
    "coverage": {
        "US Census": {
            "geoid": "37199",
            "name": "Yancey County",
            "state": "North Carolina"
        },
        "country": "us",
        "state": "nc",
        "county": "Yancey"
    },
    "data": "http://web1.mobile311.com/arcgis/rest/services/NorthCarolina/Yancey/MapServer/32",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "number": "STREET_NUM",
        "street": "STREET_NAM"
    }
}

=== 1ec5/openaddresses/sources/us-va-alexandria.json
{
    "coverage": {
        "country": "us",
        "state": "va",
        "city": "Alexandria"
    },
    "data": "http://maps.alexandriava.gov/alexmaps/rest/services/alxBasemapWm/MapServer/0",
    "type": "ESRI",
    "website": "https://www.alexandriava.gov/gis/info/default.aspx?id=7654",
    "conform": {
        "lon": "x",
        "lat": "y",
        "split": "FULL_ADDS",
        "street": "auto_street",
        "number": "auto_number",
        "type": "geojson"
    }
}

=== 1ec5/openaddresses/sources/us-oh-morrow.json
{
    "coverage": {
        "US Census": {
            "geoid": "39117",
            "name": "Morrow County",
            "state": "Ohio"
        },
        "country": "us",
        "state": "oh",
        "county": "Morrow"
    },
    "data": "http://gis3.oit.ohio.gov/LBRS/_downloads/MRW_ADDS.zip",
    "type": "http",
    "compression": "zip",
    "conform": {
        "merge": [
            "ST_NAME",
            "ST_TYPE"
        ],
        "lon": "x",
        "lat": "y",
        "number": "HOUSENUM",
        "street": "auto_street",
        "type": "shapefile",
        "postcode": "zipcode"
    }
}
