=== 1ec5/openaddresses/schema/source_schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Source",
    "description": "An OpenAddresses source",
    "type": "object",
    "required": ["type", "data", "coverage"],
    "additionalProperties": false,
    "properties": {
      "type": {
        "type": "string",
        "enum": ["http", "ftp", "ESRI"]
      },
      "data": {
        "type": "string",
        "format": "uri"
      },
      "coverage": {
        "type": "object",
        "$ref": "#/definitions/coverage"
      },
      "website": {
        "type": "string",
        "format": "uri"
      },
      "email": {
        "type": "string",
        "format": "email"
      },
      "conform": {
        "type": "object",
        "$ref": "#/definitions/conform"
      },
      "compression": {
        "type": "string"
      },
      "license": {
        "type": "string"
      },
      "note": {
        "type": "string"
      },
      "attribution": {
        "type": "string"
      },
      "language": {
        "type": "string"
      },
      "year": {
        "type": "string"
      },
      "skip": {
        "type": "boolean"
      }
    },
    "definitions": {
      "coverage": {
        "required": ["country"],
        "properties": {
          "country": {
            "type": "string"
          }
        }
      },
      "conform": {
        "properties": {
          "type": {
            "type": "string",
            "enum": ["geojson", "shapefile", "shapefile-polygon"]
          },
          "addrtype": {
            "type": "string"
          },
          "accuracy": {
            "type": "integer",
            "minimum": 0,
            "exclusiveMinimum": true
          },
          "csvsplit": {
            "type": "string"
          },
          "srs": {
            "type": "string"
          },
          "file": {
            "type": "string"
          },
          "encoding": {
            "type": "string"
          }
        }
      }
    }
}

=== 1ec5/openaddresses/sources/us/fl/orange_county.json
{
    "coverage": {
        "US Census": {
            "geoid": "12095",
            "name": "Orange County",
            "state": "Florida"
        },
        "country": "us",
        "state": "fl",
        "county": "Orange"
    },
    "attribution": "Orange County",
    "data": "ftp://ftp.onetgov.net/divisions/Infomap/pub/GIS_Downloads/FTP Shapefiles/Address Points.zip",
    "license": "Public Domain",
    "type": "ftp",
    "compression": "zip",
    "conform": {
        "type": "shapefile",
        "number": "ADDRESS__1",
        "street": "COMPLETE_S",
        "city": "MUNICIPAL_",
        "postcode": "ZIPCODE"
    }
}

=== 1ec5/openaddresses/sources/us-in-hamilton.json
{
    "coverage": {
        "US Census": {
            "geoid": "18057",
            "name": "Hamilton County",
            "state": "Indiana"
        },
        "country": "us",
        "state": "in",
        "county": "Hamilton"
    },
    "data": "http://gis.hamiltoncounty.in.gov/ArcGIS/rest/services/E911/MapServer/0",
    "type": "ESRI",
    "conform": {
        "merge": [
            "loc_st",
            "loc_st_suf"
        ],
        "lon": "x",
        "lat": "y",
        "number": "loc_no",
        "street": "auto_street",
        "type": "geojson",
        "postcode": "loc_zip"
    }
}

=== 1ec5/openaddresses/sources/us/va/essex.json
{
    "coverage": {
        "US Census": {
            "geoid": "51057",
            "name": "Essex County",
            "state": "Virginia"
        },
        "country": "us",
        "state": "va",
        "county": "Essex"
    },
    "data": "http://vcloud.timmons.com/ArcGIS/rest/services/EssexWebLogistics/Essex_Main/MapServer/8",
    "type": "ESRI",
    "conform": {
        "number": "ADDRNUM",
        "street": "FULLNAME",
        "type": "geojson",
        "postcode": "zip"
    }
}

=== 1ec5/openaddresses/sources/us/ca/kings.json
{
    "coverage": {
        "US Census": {
            "geoid": "06031",
            "name": "Kings County",
            "state": "California"
        },
        "country": "us",
        "state": "ca",
        "county": "Kings"
    },
    "conform": {
        "type": "geojson",
        "number": "STREET_NBR",
        "street": [
            "STREET_DIR",
            "STREET_NAM",
            "STREET_TYP"
        ],
        "city": "COMMUNITY",
        "postcode": "ZIPCODE"
    },
    "attribution": "Kings County",
    "data": "http://maps.co.kern.ca.us/arcgis/rest/services/Kings_base5all/MapServer/113",
    "type": "ESRI"
}

=== 1ec5/openaddresses/sources/us/nc/chowan.json
{
    "coverage": {
        "US Census": {"geoid": "37041", "name": "Chowan County", "state": "North Carolina"},
        "country": "us",
        "state": "nc",
        "county": "Chowan"
    },
    "data": "",
    "type": "http",
    "compression": "zip",
    "website": "http://data.nconemap.gov/downloads/vector/parcels/Chowan_parcels_2017_10_26.zip",
    "conform": {
        "type": "shapefile",
        "file": "nc_chowan_parcels_pt_2017_10_26.shp",
        "id": "PARNO",
        "number": {
            "function": "prefixed_number",
            "field": "SITEADD"
        },
        "street": {
            "function": "postfixed_street",
            "field": "SITEADD"
        }
    }
}

=== 1ec5/openaddresses/sources/us/ct/trumbull.json
{
    "coverage": {
        "country": "us",
        "state": "ct",
        "city": "Trumbull"
    },
    "data": "https://gis.gbrct.org:6443/arcgis/rest/services/Trumbull/Trumbull_Parcels_NAD83/MapServer/4",
    "website": "http://www.trumbull-ct.gov/",
    "type": "ESRI",
    "conform": {
        "type": "geojson",
        "split": "Location",
        "number": "ST_NUM",
        "street": "auto_street",
        "id": "PAR_ID",
        "accuracy": 2
    }
}

=== 1ec5/openaddresses/sources/us-va-city_of_emporia.json
{
    "coverage": {
        "country": "us",
        "state": "va",
        "city": "Emporia"
    },
    "data": "http://gis.worldviewsolutions.com/arcgis/rest/services/emporia/main/MapServer/8",
    "type": "ESRI",
    "conform": {
        "lon": "x",
        "lat": "y",
        "number": "str_num",
        "street": "str_name",
        "type": "geojson"
    }
}

=== 1ec5/openaddresses/sources/us-hi-honolulu.json
{
    "coverage": {
      "country": "us",
      "state": "hi",
      "county": "honolulu",
      "city": "honolulu"
    },
    "attribution": "City of Honolulu",
    "data": "https://www.dropbox.com/s/94da2ic6a5c2j50/us-hi-honolulu.zip?dl=0",
    "website": "ftp://gisftp.hicentral.com/Layers/Cadastral/",
    "license": "",
    "year": "2012",
    "type": "http",
    "compression": "zip",
    "note": "Includes full parcel shapefile of the island of Oahu. SRS is EPSG: 2784 "
}
